replicaCount: 2

image:
  repository: ghcr.io/esuen/launchpad
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  port: "8080"

secret:
  databaseURL: "postgres://launchpad:launchpad@postgresql:5432/launchpad?sslmode=disable"

ingress:
  host: launchpad.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
