replicaCount: 1

image:
  tag: 2d8f6315cd146d9922720bac70e909441655eb9e
  pullPolicy: IfNotPresent

secret:
  databaseURL: "postgres://launchpad:launchpad@postgresql.default.svc.cluster.local:5432/launchpad?sslmode=disable"

ingress:
  host: staging.launchpad.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
