replicaCount: 2

image:
  tag: 2d8f6315cd146d9922720bac70e909441655eb9e
  pullPolicy: IfNotPresent

secret:
  databaseURL: "postgres://launchpad:launchpad@postgresql.default.svc.cluster.local:5432/launchpad?sslmode=disable"

ingress:
  host: launchpad.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
