replicaCount: 1

image:
  tag: efcca1dc10c544a5a57b99c5db2abd29a2969750
  pullPolicy: IfNotPresent

secret:
  databaseURL: "postgres://launchpad:launchpad@postgresql.default.svc.cluster.local:5432/launchpad?sslmode=disable"

ingress:
  host: staging.launchpad.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
