replicaCount: 2

image:
  tag: 89488df5cedb171cdd1e1f30b26ccdf2bb384ca4
  pullPolicy: IfNotPresent

secret:
  databaseURL: "postgres://launchpad:launchpad@postgresql.default.svc.cluster.local:5432/launchpad?sslmode=disable"

ingress:
  host: launchpad.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

canary:
  steps:
    - setWeight: 10
    - pause: {}
    - setWeight: 25
    - pause: {}
    - setWeight: 50
    - pause: {}
    - setWeight: 75
    - pause: {}
